// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BulkActionAuditItemKind.
const (
	BulkActionAuditItemKindAfter    BulkActionAuditItemKind = "after"
	BulkActionAuditItemKindBefore   BulkActionAuditItemKind = "before"
	BulkActionAuditItemKindOther    BulkActionAuditItemKind = "other"
	BulkActionAuditItemKindRollback BulkActionAuditItemKind = "rollback"
)

// Defines values for BulkActionOperationStatus.
const (
	Completed BulkActionOperationStatus = "completed"
	Failed    BulkActionOperationStatus = "failed"
	Queued    BulkActionOperationStatus = "queued"
	Running   BulkActionOperationStatus = "running"
)

// Defines values for BulkActionPlanActionsType.
const (
	BulkActionPlanActionsTypeADJUSTBUDGET BulkActionPlanActionsType = "ADJUST_BUDGET"
	BulkActionPlanActionsTypeADJUSTCPC    BulkActionPlanActionsType = "ADJUST_CPC"
	BulkActionPlanActionsTypeROTATELINK   BulkActionPlanActionsType = "ROTATE_LINK"
)

// Defines values for KeywordIdeaCompetition.
const (
	HIGH   KeywordIdeaCompetition = "HIGH"
	LOW    KeywordIdeaCompetition = "LOW"
	MEDIUM KeywordIdeaCompetition = "MEDIUM"
)

// Defines values for MccLinkStatus.
const (
	MccLinkStatusActive   MccLinkStatus = "active"
	MccLinkStatusInactive MccLinkStatus = "inactive"
	MccLinkStatusInvited  MccLinkStatus = "invited"
	MccLinkStatusPending  MccLinkStatus = "pending"
)

// Defines values for ValidationViolationSeverity.
const (
	Error ValidationViolationSeverity = "error"
	Info  ValidationViolationSeverity = "info"
	Warn  ValidationViolationSeverity = "warn"
)

// Defines values for SubmitBulkActionsJSONBodyActionsType.
const (
	SubmitBulkActionsJSONBodyActionsTypeADJUSTBUDGET SubmitBulkActionsJSONBodyActionsType = "ADJUST_BUDGET"
	SubmitBulkActionsJSONBodyActionsTypeADJUSTCPC    SubmitBulkActionsJSONBodyActionsType = "ADJUST_CPC"
	SubmitBulkActionsJSONBodyActionsTypeROTATELINK   SubmitBulkActionsJSONBodyActionsType = "ROTATE_LINK"
)

// Defines values for GetRollbackReportParamsKind.
const (
	GetRollbackReportParamsKindRollback     GetRollbackReportParamsKind = "rollback"
	GetRollbackReportParamsKindRollbackExec GetRollbackReportParamsKind = "rollback_exec"
)

// Defines values for ListMccLinksParamsStatus.
const (
	ListMccLinksParamsStatusActive   ListMccLinksParamsStatus = "active"
	ListMccLinksParamsStatusInactive ListMccLinksParamsStatus = "inactive"
	ListMccLinksParamsStatusInvited  ListMccLinksParamsStatus = "invited"
	ListMccLinksParamsStatusPending  ListMccLinksParamsStatus = "pending"
)

// AdsConnection defines model for AdsConnection.
type AdsConnection struct {
	LoginCustomerId   *string    `json:"loginCustomerId,omitempty"`
	PrimaryCustomerId *string    `json:"primaryCustomerId,omitempty"`
	UpdatedAt         *time.Time `json:"updatedAt,omitempty"`
}

// AuditEventItem defines model for AuditEventItem.
type AuditEventItem struct {
	CreatedAt time.Time              `json:"createdAt"`
	Data      map[string]interface{} `json:"data"`
	Kind      string                 `json:"kind"`
}

// BulkActionAuditItem defines model for BulkActionAuditItem.
type BulkActionAuditItem struct {
	CreatedAt time.Time               `json:"createdAt"`
	Kind      BulkActionAuditItemKind `json:"kind"`
	Snapshot  map[string]interface{}  `json:"snapshot"`
}

// BulkActionAuditItemKind defines model for BulkActionAuditItem.Kind.
type BulkActionAuditItemKind string

// BulkActionOperation defines model for BulkActionOperation.
type BulkActionOperation struct {
	CreatedAt   *time.Time                `json:"createdAt,omitempty"`
	OperationId string                    `json:"operationId"`
	Status      BulkActionOperationStatus `json:"status"`
	Summary     *struct {
		Actions           *int `json:"actions,omitempty"`
		EstimatedAffected *int `json:"estimatedAffected,omitempty"`
	} `json:"summary,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// BulkActionOperationStatus defines model for BulkActionOperation.Status.
type BulkActionOperationStatus string

// BulkActionPlan defines model for BulkActionPlan.
type BulkActionPlan struct {
	Actions []struct {
		Filter *map[string]interface{}    `json:"filter,omitempty"`
		Params *map[string]interface{}    `json:"params,omitempty"`
		Type   *BulkActionPlanActionsType `json:"type,omitempty"`
	} `json:"actions"`
	ValidateOnly *bool `json:"validateOnly,omitempty"`
}

// BulkActionPlanActionsType defines model for BulkActionPlan.Actions.Type.
type BulkActionPlanActionsType string

// BulkActionValidationResult defines model for BulkActionValidationResult.
type BulkActionValidationResult struct {
	Errors  *[]string `json:"errors,omitempty"`
	Ok      bool      `json:"ok"`
	Summary struct {
		Actions           *int `json:"actions,omitempty"`
		EstimatedAffected *int `json:"estimatedAffected,omitempty"`
	} `json:"summary"`
	Violations *[]ValidationViolation `json:"violations,omitempty"`
	Warnings   *[]string              `json:"warnings,omitempty"`
}

// KeywordIdea defines model for KeywordIdea.
type KeywordIdea struct {
	AvgMonthlySearches int                    `json:"avgMonthlySearches"`
	Competition        KeywordIdeaCompetition `json:"competition"`
	Keyword            string                 `json:"keyword"`
}

// KeywordIdeaCompetition defines model for KeywordIdea.Competition.
type KeywordIdeaCompetition string

// MccLink defines model for MccLink.
type MccLink struct {
	CustomerId string        `json:"customerId"`
	Status     MccLinkStatus `json:"status"`
	UpdatedAt  *time.Time    `json:"updatedAt,omitempty"`
}

// MccLinkStatus defines model for MccLink.Status.
type MccLinkStatus string

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	ActionIndex *int                         `json:"actionIndex,omitempty"`
	Code        *string                      `json:"code,omitempty"`
	Field       *string                      `json:"field,omitempty"`
	Message     *string                      `json:"message,omitempty"`
	Severity    *ValidationViolationSeverity `json:"severity,omitempty"`
}

// ValidationViolationSeverity defines model for ValidationViolation.Severity.
type ValidationViolationSeverity string

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	Kind  *string    `form:"kind,omitempty" json:"kind,omitempty"`
	Limit *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`
}

// ListBulkActionsParams defines parameters for ListBulkActions.
type ListBulkActionsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SubmitBulkActionsJSONBody defines parameters for SubmitBulkActions.
type SubmitBulkActionsJSONBody struct {
	Actions *[]struct {
		// Filter Filter conditions (implementation-defined)
		Filter *map[string]interface{} `json:"filter,omitempty"`

		// Params Action parameters (implementation-defined)
		Params *map[string]interface{} `json:"params,omitempty"`

		// Type Action type
		Type *SubmitBulkActionsJSONBodyActionsType `json:"type,omitempty"`
	} `json:"actions,omitempty"`
	ValidateOnly *bool `json:"validateOnly,omitempty"`
}

// SubmitBulkActionsJSONBodyActionsType defines parameters for SubmitBulkActions.
type SubmitBulkActionsJSONBodyActionsType string

// GetRollbackReportParams defines parameters for GetRollbackReport.
type GetRollbackReportParams struct {
	Kind *GetRollbackReportParamsKind `form:"kind,omitempty" json:"kind,omitempty"`
}

// GetRollbackReportParamsKind defines parameters for GetRollbackReport.
type GetRollbackReportParamsKind string

// ExpandKeywordsJSONBody defines parameters for ExpandKeywords.
type ExpandKeywordsJSONBody struct {
	SeedDomain   *string   `json:"seedDomain,omitempty"`
	SeedKeywords *[]string `json:"seedKeywords,omitempty"`

	// ValidateOnly If true, returns stub suggestions without live API calls
	ValidateOnly *bool `json:"validateOnly,omitempty"`
}

// MccLinkJSONBody defines parameters for MccLink.
type MccLinkJSONBody struct {
	CustomerId string `json:"customerId"`
}

// ListMccLinksParams defines parameters for ListMccLinks.
type ListMccLinksParams struct {
	Status *ListMccLinksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListMccLinksParamsStatus defines parameters for ListMccLinks.
type ListMccLinksParamsStatus string

// MccRefreshJSONBody defines parameters for MccRefresh.
type MccRefreshJSONBody struct {
	Shard       *int `json:"shard,omitempty"`
	TotalShards *int `json:"totalShards,omitempty"`
}

// MccStatusParams defines parameters for MccStatus.
type MccStatusParams struct {
	CustomerId string `form:"customerId" json:"customerId"`
}

// MccUnlinkJSONBody defines parameters for MccUnlink.
type MccUnlinkJSONBody struct {
	CustomerId string `json:"customerId"`
}

// RunPreflightJSONBody defines parameters for RunPreflight.
type RunPreflightJSONBody struct {
	// AccountId Google Ads customer id (10 digits)
	AccountId *string `json:"accountId,omitempty"`

	// LandingUrl Optional landing page URL to check reachability
	LandingUrl *string `json:"landingUrl,omitempty"`

	// ValidateOnly If true, skip live checks and only validate environment/config
	ValidateOnly *bool `json:"validateOnly,omitempty"`
}

// SubmitBulkActionsJSONRequestBody defines body for SubmitBulkActions for application/json ContentType.
type SubmitBulkActionsJSONRequestBody SubmitBulkActionsJSONBody

// ValidateBulkActionsJSONRequestBody defines body for ValidateBulkActions for application/json ContentType.
type ValidateBulkActionsJSONRequestBody = BulkActionPlan

// ExpandKeywordsJSONRequestBody defines body for ExpandKeywords for application/json ContentType.
type ExpandKeywordsJSONRequestBody ExpandKeywordsJSONBody

// MccLinkJSONRequestBody defines body for MccLink for application/json ContentType.
type MccLinkJSONRequestBody MccLinkJSONBody

// MccRefreshJSONRequestBody defines body for MccRefresh for application/json ContentType.
type MccRefreshJSONRequestBody MccRefreshJSONBody

// MccUnlinkJSONRequestBody defines body for MccUnlink for application/json ContentType.
type MccUnlinkJSONRequestBody MccUnlinkJSONBody

// RunPreflightJSONRequestBody defines body for RunPreflight for application/json ContentType.
type RunPreflightJSONRequestBody RunPreflightJSONBody
