// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// SubmitBulkActionsJSONBody defines parameters for SubmitBulkActions.
type SubmitBulkActionsJSONBody = map[string]interface{}

// RunPreflightJSONBody defines parameters for RunPreflight.
type RunPreflightJSONBody = map[string]interface{}

// SubmitBulkActionsJSONRequestBody defines body for SubmitBulkActions for application/json ContentType.
type SubmitBulkActionsJSONRequestBody = SubmitBulkActionsJSONBody

// RunPreflightJSONRequestBody defines body for RunPreflight for application/json ContentType.
type RunPreflightJSONRequestBody = RunPreflightJSONBody
