name: Deploy to Cloud Run and Firebase Hosting (archived)

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ vars.GCP_PROJECT_ID }}'

  deploy-services:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    strategy:
      matrix:
        service: [identity, billing, offer, siterank, batchopen, adscenter, workflow]
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ matrix.service }}:latest services/${{ matrix.service }}
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy '${{ matrix.service }}' \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ matrix.service }}:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
