version: '3.8'
services:
  console:
    build:
      context: ./services/console
    ports:
      - "8080:8080" # Mapped to port 8080 for the admin proxy
    environment:
      - DATABASE_URL_SECRET_NAME=${DATABASE_URL_SECRET_NAME}
    depends_on:
      - cloudsql-proxy
  identity:
    build:
      context: ./services/identity
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL_SECRET_NAME=${DATABASE_URL_SECRET_NAME}
      - FIREBASE_CREDENTIALS_FILE=/app/secrets/firebase-adminsdk.json
    depends_on:
      - cloudsql-proxy
    volumes:
      - ./secrets/firebase-adminsdk.json:/app/secrets/firebase-adminsdk.json:ro
  billing:
    build:
      context: ./services/billing
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL_SECRET_NAME=${DATABASE_URL_SECRET_NAME}
    depends_on:
      - cloudsql-proxy
    volumes:
      - ./secrets/firebase-adminsdk.json:/app/secrets/firebase-adminsdk.json:ro
  offer:
    build:
      context: ./services/offer
    ports:
      - "8083:8080"
    environment:
      - DATABASE_URL_SECRET_NAME=${DATABASE_URL_SECRET_NAME}
    depends_on:
      - cloudsql-proxy
    volumes:
      - ./secrets/firebase-adminsdk.json:/app/secrets/firebase-adminsdk.json:ro
  siterank:
    build:
      context: ./services/siterank
    ports:
      - "8084:8080"
    environment:
      - DATABASE_URL_SECRET_NAME=${DATABASE_URL_SECRET_NAME}
      - SITERANK_SERVICE_URL=http://siterank:8080
    depends_on:
      - cloudsql-proxy
  batchopen:
    build:
      context: ./services/batchopen
    ports:
      - "8085:8080"
    environment:
      - DATABASE_URL_SECRET_NAME=${DATABASE_URL_SECRET_NAME}
    depends_on:
      - cloudsql-proxy
  adscenter:
    build:
      context: ./services/adscenter
    ports:
      - "8086:8080"
    environment:
      - DATABASE_URL_SECRET_NAME=${DATABASE_URL_SECRET_NAME}
    depends_on:
      - cloudsql-proxy
    volumes:
      - ./secrets/firebase-adminsdk.json:/app/secrets/firebase-adminsdk.json:ro
  workflow:
    build:
      context: ./services/workflow
    ports:
      - "8087:8080"
    environment:
      - DATABASE_URL_SECRET_NAME=${DATABASE_URL_SECRET_NAME}
      - SITERANK_SERVICE_URL=http://siterank:8080 # For inter-service communication
    depends_on:
      - cloudsql-proxy
    volumes:
      - ./secrets/firebase-adminsdk.json:/app/secrets/firebase-adminsdk.json:ro
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - WORKFLOW_SERVICE_URL=http://workflow:8080
      - NEXTAUTH_URL=http://localhost:3000 # For OAuth callbacks
    depends_on:
      - console
      - workflow
      - siterank

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
    command: ["--private-ip", "--port", "5432", "${CLOUDSQL_CONNECTION_NAME}"]
    ports:
      - "5432:5432"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/secrets/key.json:ro
