openapi: 3.0.0
info:
  title: Identity Service
  version: 1.0.0
  description: Handles user authentication, registration, and profile management.
paths:
  /api/v1/identity/register:
    post:
      summary: Idempotent register current Firebase-authenticated user
      security:
        - bearerAuth: []
      responses:
        '202':
          description: Registration accepted (or already exists)
  /api/v1/identity/me:
    get:
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
