// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OfferStatus.
const (
	Archived   OfferStatus = "archived"
	Evaluating OfferStatus = "evaluating"
	Optimizing OfferStatus = "optimizing"
	Scaling    OfferStatus = "scaling"
)

// Error defines model for Error.
type Error struct {
	Error *struct {
		Code    string      `json:"code"`
		Details interface{} `json:"details,omitempty"`
		Message string      `json:"message"`
		TraceId *string     `json:"traceId,omitempty"`
	} `json:"error,omitempty"`
}

// Offer defines model for Offer.
type Offer struct {
	CreatedAt     time.Time   `json:"createdAt"`
	Id            string      `json:"id"`
	Name          string      `json:"name"`
	OriginalUrl   string      `json:"originalUrl"`
	SiterankScore *float32    `json:"siterankScore"`
	Status        OfferStatus `json:"status"`
	UserId        string      `json:"userId"`
}

// OfferStatus defines model for Offer.Status.
type OfferStatus string

// OfferCreateRequest defines model for OfferCreateRequest.
type OfferCreateRequest struct {
	Name        string `json:"name"`
	OriginalUrl string `json:"originalUrl"`
}

// OfferCreatedEvent defines model for OfferCreatedEvent.
type OfferCreatedEvent struct {
	CreatedAt   time.Time `json:"createdAt"`
	Name        string    `json:"name"`
	OfferId     string    `json:"offerId"`
	OriginalUrl string    `json:"originalUrl"`
	Status      string    `json:"status"`
	UserId      string    `json:"userId"`
}

// CreateOfferJSONRequestBody defines body for CreateOffer for application/json ContentType.
type CreateOfferJSONRequestBody = OfferCreateRequest
