// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OfferStatus.
const (
	Archived   OfferStatus = "archived"
	Evaluating OfferStatus = "evaluating"
	Optimizing OfferStatus = "optimizing"
	Scaling    OfferStatus = "scaling"
)

// Defines values for OfferStatusUpdatedStatus.
const (
	Ok OfferStatusUpdatedStatus = "ok"
)

// Error defines model for Error.
type Error struct {
	Error *struct {
		Code    string      `json:"code"`
		Details interface{} `json:"details,omitempty"`
		Message string      `json:"message"`
		TraceId *string     `json:"traceId,omitempty"`
	} `json:"error,omitempty"`
}

// Offer defines model for Offer.
type Offer struct {
	CreatedAt     time.Time   `json:"createdAt"`
	Id            string      `json:"id"`
	Name          string      `json:"name"`
	OriginalUrl   string      `json:"originalUrl"`
	SiterankScore *float32    `json:"siterankScore"`
	Status        OfferStatus `json:"status"`
	UserId        string      `json:"userId"`
}

// OfferStatus defines model for Offer.Status.
type OfferStatus string

// OfferCreateRequest defines model for OfferCreateRequest.
type OfferCreateRequest struct {
	Name        string `json:"name"`
	OriginalUrl string `json:"originalUrl"`
}

// OfferCreatedEvent defines model for OfferCreatedEvent.
type OfferCreatedEvent struct {
	CreatedAt   time.Time `json:"createdAt"`
	Name        string    `json:"name"`
	OfferId     string    `json:"offerId"`
	OriginalUrl string    `json:"originalUrl"`
	Status      string    `json:"status"`
	UserId      string    `json:"userId"`
}

// OfferKpiResponse defines model for OfferKpiResponse.
type OfferKpiResponse struct {
	Days []struct {
		Clicks      int64              `json:"clicks"`
		Date        openapi_types.Date `json:"date"`
		Impressions int64              `json:"impressions"`
		Revenue     float32            `json:"revenue"`
		Spend       float32            `json:"spend"`
	} `json:"days"`
	Summary struct {
		Clicks      int64   `json:"clicks"`
		Impressions int64   `json:"impressions"`
		Revenue     float32 `json:"revenue"`
		Rosc        float32 `json:"rosc"`
		Spend       float32 `json:"spend"`
	} `json:"summary"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// OfferStatusUpdate defines model for OfferStatusUpdate.
type OfferStatusUpdate struct {
	Status string `json:"status"`
}

// OfferStatusUpdated defines model for OfferStatusUpdated.
type OfferStatusUpdated struct {
	From    string                   `json:"from"`
	OfferId string                   `json:"offerId"`
	Status  OfferStatusUpdatedStatus `json:"status"`
	To      string                   `json:"to"`
}

// OfferStatusUpdatedStatus defines model for OfferStatusUpdated.Status.
type OfferStatusUpdatedStatus string

// OfferUpdateRequest defines model for OfferUpdateRequest.
type OfferUpdateRequest struct {
	Name        *string `json:"name,omitempty"`
	OriginalUrl *string `json:"originalUrl,omitempty"`
}

// CreateOfferJSONRequestBody defines body for CreateOffer for application/json ContentType.
type CreateOfferJSONRequestBody = OfferCreateRequest

// UpdateOfferJSONRequestBody defines body for UpdateOffer for application/json ContentType.
type UpdateOfferJSONRequestBody = OfferUpdateRequest

// UpdateOfferStatusJSONRequestBody defines body for UpdateOfferStatus for application/json ContentType.
type UpdateOfferStatusJSONRequestBody = OfferStatusUpdate
