// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BrandCheckItemMethod.
const (
	BrandCheckItemMethodExact BrandCheckItemMethod = "exact"
	BrandCheckItemMethodFuzzy BrandCheckItemMethod = "fuzzy"
	BrandCheckItemMethodNone  BrandCheckItemMethod = "none"
)

// Defines values for BrandCheckItemSeverity.
const (
	BrandCheckItemSeverityError BrandCheckItemSeverity = "error"
	BrandCheckItemSeverityNone  BrandCheckItemSeverity = "none"
	BrandCheckItemSeverityWarn  BrandCheckItemSeverity = "warn"
)

// Defines values for ListBrandResultsParamsSeverity.
const (
	Error ListBrandResultsParamsSeverity = "error"
	None  ListBrandResultsParamsSeverity = "none"
	Warn  ListBrandResultsParamsSeverity = "warn"
)

// BrandCheckItem defines model for BrandCheckItem.
type BrandCheckItem struct {
	ContainsBrand bool                   `json:"containsBrand"`
	Keyword       string                 `json:"keyword"`
	MatchedAlias  *string                `json:"matchedAlias,omitempty"`
	Method        BrandCheckItemMethod   `json:"method"`
	Score         *float32               `json:"score,omitempty"`
	Severity      BrandCheckItemSeverity `json:"severity"`
}

// BrandCheckItemMethod defines model for BrandCheckItem.Method.
type BrandCheckItemMethod string

// BrandCheckItemSeverity defines model for BrandCheckItem.Severity.
type BrandCheckItemSeverity string

// BrandCoverageResult defines model for BrandCoverageResult.
type BrandCoverageResult struct {
	AccountId      string     `json:"accountId"`
	BrandKeywords  int        `json:"brandKeywords"`
	CoverageRatio  float32    `json:"coverageRatio"`
	MissingAliases *[]string  `json:"missingAliases,omitempty"`
	SeedDomain     string     `json:"seedDomain"`
	TotalKeywords  int        `json:"totalKeywords"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
}

// GetBrandCoverageParams defines parameters for GetBrandCoverage.
type GetBrandCoverageParams struct {
	SeedDomain string `form:"seedDomain" json:"seedDomain"`
	AccountId  string `form:"accountId" json:"accountId"`
}

// GetPlannedBrandCoverageJSONBody defines parameters for GetPlannedBrandCoverage.
type GetPlannedBrandCoverageJSONBody struct {
	Keywords   []string `json:"keywords"`
	SeedDomain string   `json:"seedDomain"`
}

// OfflineBrandAuditJSONBody defines parameters for OfflineBrandAudit.
type OfflineBrandAuditJSONBody struct {
	AccountId  *string   `json:"accountId,omitempty"`
	Days       *int      `json:"days,omitempty"`
	Keywords   *[]string `json:"keywords,omitempty"`
	Limit      *int      `json:"limit,omitempty"`
	SeedDomain string    `json:"seedDomain"`

	// Shard optional shard index (0-based)
	Shard *int `json:"shard,omitempty"`

	// TotalShards optional shard count (>0)
	TotalShards *int `json:"totalShards,omitempty"`
}

// OfflineBrandCoverageAuditJSONBody defines parameters for OfflineBrandCoverageAudit.
type OfflineBrandCoverageAuditJSONBody struct {
	AccountId   *string `json:"accountId,omitempty"`
	Days        *int    `json:"days,omitempty"`
	SeedDomain  string  `json:"seedDomain"`
	Shard       *int    `json:"shard,omitempty"`
	TotalShards *int    `json:"totalShards,omitempty"`
}

// BrandCheckJSONBody defines parameters for BrandCheck.
type BrandCheckJSONBody struct {
	Keywords []string `json:"keywords"`

	// LandingUrl Optional landing page URL to extract brand signals
	LandingUrl *string `json:"landingUrl,omitempty"`
	Locale     *string `json:"locale,omitempty"`
	SeedDomain string  `json:"seedDomain"`
}

// GetBrandProfileParams defines parameters for GetBrandProfile.
type GetBrandProfileParams struct {
	SeedDomain string `form:"seedDomain" json:"seedDomain"`
}

// ListBrandResultsParams defines parameters for ListBrandResults.
type ListBrandResultsParams struct {
	SeedDomain    string                          `form:"seedDomain" json:"seedDomain"`
	Limit         *int                            `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor        *string                         `form:"cursor,omitempty" json:"cursor,omitempty"`
	Severity      *ListBrandResultsParamsSeverity `form:"severity,omitempty" json:"severity,omitempty"`
	ContainsBrand *bool                           `form:"containsBrand,omitempty" json:"containsBrand,omitempty"`
}

// ListBrandResultsParamsSeverity defines parameters for ListBrandResults.
type ListBrandResultsParamsSeverity string

// GetPlannedBrandCoverageJSONRequestBody defines body for GetPlannedBrandCoverage for application/json ContentType.
type GetPlannedBrandCoverageJSONRequestBody GetPlannedBrandCoverageJSONBody

// OfflineBrandAuditJSONRequestBody defines body for OfflineBrandAudit for application/json ContentType.
type OfflineBrandAuditJSONRequestBody OfflineBrandAuditJSONBody

// OfflineBrandCoverageAuditJSONRequestBody defines body for OfflineBrandCoverageAudit for application/json ContentType.
type OfflineBrandCoverageAuditJSONRequestBody OfflineBrandCoverageAuditJSONBody

// BrandCheckJSONRequestBody defines body for BrandCheck for application/json ContentType.
type BrandCheckJSONRequestBody BrandCheckJSONBody
