name: "[ARCHIVED] Debug GitHub Actions Permissions"

on:
  workflow_dispatch:

jobs:
  debug-permissions:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test API access
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Testing GitHub API access..."
          
          # Test repository access
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}
          
          # Test workflow runs access
          echo "Testing workflow runs access..."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/runs
          
          # Test current run access
          echo "Testing current run access..."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
      - name: Create dummy SARIF file
        run: |
          cat > dummy.sarif << EOF
          {
            "version": "2.1.0",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "TestTool",
                    "version": "1.0.0"
                  }
                },
                "results": []
              }
            ]
          }
          EOF
      
      - name: Check Code Scanning status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking Code Scanning status..."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts || echo "Code Scanning not enabled or no alerts"
      
      - name: Test SARIF upload (will fail if Code Scanning not enabled)
        uses: github/codeql-action/upload-sarif@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sarif_file: dummy.sarif
        continue-on-error: true
