steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'apps/frontend'
  args: ['build','-f','Dockerfile','-t','asia-northeast1-docker.pkg.dev/gen-lang-client-0944935873/autoads-services/frontend:latest','.']
images: ['asia-northeast1-docker.pkg.dev/gen-lang-client-0944935873/autoads-services/frontend:latest']
