// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateBatchopenTaskJSONBody defines parameters for CreateBatchopenTask.
type CreateBatchopenTaskJSONBody struct {
	OfferId          string                  `json:"offerId"`
	SimulationConfig *map[string]interface{} `json:"simulationConfig,omitempty"`
}

// CreateBatchopenTaskJSONRequestBody defines body for CreateBatchopenTask for application/json ContentType.
type CreateBatchopenTaskJSONRequestBody CreateBatchopenTaskJSONBody
