// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateBatchopenTaskJSONBody defines parameters for CreateBatchopenTask.
type CreateBatchopenTaskJSONBody struct {
	OfferId          string                  `json:"offerId"`
	SimulationConfig *map[string]interface{} `json:"simulationConfig,omitempty"`
}

// CompleteBatchopenTaskJSONBody defines parameters for CompleteBatchopenTask.
type CompleteBatchopenTaskJSONBody map[string]interface{}

// FailBatchopenTaskJSONBody defines parameters for FailBatchopenTask.
type FailBatchopenTaskJSONBody struct {
	Reason *string `json:"reason,omitempty"`
}

// CreateBatchopenTaskJSONRequestBody defines body for CreateBatchopenTask for application/json ContentType.
type CreateBatchopenTaskJSONRequestBody CreateBatchopenTaskJSONBody

// CompleteBatchopenTaskJSONRequestBody defines body for CompleteBatchopenTask for application/json ContentType.
type CompleteBatchopenTaskJSONRequestBody CompleteBatchopenTaskJSONBody

// FailBatchopenTaskJSONRequestBody defines body for FailBatchopenTask for application/json ContentType.
type FailBatchopenTaskJSONRequestBody FailBatchopenTaskJSONBody
