// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Subscription defines model for Subscription.
type Subscription struct {
	CurrentPeriodEnd time.Time `json:"currentPeriodEnd"`
	Id               string    `json:"id"`
	PlanName         string    `json:"planName"`
	Status           string    `json:"status"`
}

// TokenTransaction defines model for TokenTransaction.
type TokenTransaction struct {
	Amount      int       `json:"amount"`
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description,omitempty"`
	Id          string    `json:"id"`
	Type        string    `json:"type"`
}
