openapi: 3.0.0
info:
  title: Billing Service
  version: 1.0.0
  description: Handles subscriptions, plans, and token management.
paths:
  /api/v1/billing/subscriptions/me:
    get:
      summary: Get current user's subscription
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Subscription
  /api/v1/billing/tokens/me:
    get:
      summary: Get current user's token balance
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token balance
  /api/v1/billing/tokens/transactions:
    get:
      summary: List token transactions for current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of token transactions
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
