openapi: 3.0.3
info:
  title: Workflow Service
  description: API for managing workflows in the AutoAds platform.
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
paths:
  /workflows/start:
    post:
      summary: Start a new workflow
      description: Initiates a new workflow instance based on a template for a specific offer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: The ID of the user initiating the workflow.
                template_id:
                  type: string
                  description: The ID of the workflow template to use.
                offer_id:
                  type: string
                  description: The ID of the offer this workflow is associated with.
      responses:
        '202':
          description: Workflow instance successfully started.
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflow_instance_id:
                    type: string
                    description: The unique ID of the newly created workflow instance.
        '400':
          description: Bad request (e.g., missing parameters).
        '401':
          description: Unauthorized.
        '500':
          description: Internal Server Error.
