// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AnalysisStatus.
const (
	Completed AnalysisStatus = "completed"
	Failed    AnalysisStatus = "failed"
	Pending   AnalysisStatus = "pending"
	Running   AnalysisStatus = "running"
)

// Analysis defines model for Analysis.
type Analysis struct {
	CreatedAt time.Time               `json:"createdAt"`
	Id        string                  `json:"id"`
	OfferId   string                  `json:"offerId"`
	Result    *map[string]interface{} `json:"result"`
	Status    AnalysisStatus          `json:"status"`
	UpdatedAt time.Time               `json:"updatedAt"`
	UserId    string                  `json:"userId"`
}

// AnalysisStatus defines model for Analysis.Status.
type AnalysisStatus string

// HistoryItem defines model for HistoryItem.
type HistoryItem struct {
	AnalysisId string                  `json:"analysisId"`
	CreatedAt  time.Time               `json:"createdAt"`
	OfferId    string                  `json:"offerId"`
	Result     *map[string]interface{} `json:"result"`
	Score      int                     `json:"score"`
	UserId     string                  `json:"userId"`
}

// KeywordSuggestion defines model for KeywordSuggestion.
type KeywordSuggestion struct {
	Keyword string `json:"keyword"`

	// Reason brief why this keyword was suggested
	Reason *string `json:"reason,omitempty"`

	// Score 0..1
	Score float32 `json:"score"`
}

// SimilarityItem defines model for SimilarityItem.
type SimilarityItem struct {
	Domain  string                  `json:"domain"`
	Factors *map[string]interface{} `json:"factors,omitempty"`
	Score   float32                 `json:"score"`
}

// TrendPoint defines model for TrendPoint.
type TrendPoint struct {
	AvgScore float32 `json:"avgScore"`
	Count    int     `json:"count"`

	// Date YYYY-MM-DD
	Date string `json:"date"`
}

// RequestSiterankAnalysisJSONBody defines parameters for RequestSiterankAnalysis.
type RequestSiterankAnalysisJSONBody struct {
	OfferId string `json:"offerId"`
}

// SuggestKeywordsJSONBody defines parameters for SuggestKeywords.
type SuggestKeywordsJSONBody struct {
	// Country Optional ISO country code
	Country *string `json:"country,omitempty"`

	// MinScore 0..1 score threshold
	MinScore *float32 `json:"minScore,omitempty"`

	// SeedDomain Domain to analyze
	SeedDomain string `json:"seedDomain"`
	TopN       *int   `json:"topN,omitempty"`
}

// ComputeSimilarOffersJSONBody defines parameters for ComputeSimilarOffers.
type ComputeSimilarOffersJSONBody struct {
	Candidates []string `json:"candidates"`

	// Country Optional ISO country code
	Country    *string `json:"country,omitempty"`
	SeedDomain string  `json:"seedDomain"`
}

// GetSiterankHistoryParams defines parameters for GetSiterankHistory.
type GetSiterankHistoryParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// GetSiterankTrendParams defines parameters for GetSiterankTrend.
type GetSiterankTrendParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// RequestSiterankAnalysisJSONRequestBody defines body for RequestSiterankAnalysis for application/json ContentType.
type RequestSiterankAnalysisJSONRequestBody RequestSiterankAnalysisJSONBody

// SuggestKeywordsJSONRequestBody defines body for SuggestKeywords for application/json ContentType.
type SuggestKeywordsJSONRequestBody SuggestKeywordsJSONBody

// ComputeSimilarOffersJSONRequestBody defines body for ComputeSimilarOffers for application/json ContentType.
type ComputeSimilarOffersJSONRequestBody ComputeSimilarOffersJSONBody
