// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AnalysisStatus.
const (
	Completed AnalysisStatus = "completed"
	Failed    AnalysisStatus = "failed"
	Pending   AnalysisStatus = "pending"
	Running   AnalysisStatus = "running"
)

// Analysis defines model for Analysis.
type Analysis struct {
	CreatedAt time.Time               `json:"createdAt"`
	Id        string                  `json:"id"`
	OfferId   string                  `json:"offerId"`
	Result    *map[string]interface{} `json:"result"`
	Status    AnalysisStatus          `json:"status"`
	UpdatedAt time.Time               `json:"updatedAt"`
	UserId    string                  `json:"userId"`
}

// AnalysisStatus defines model for Analysis.Status.
type AnalysisStatus string

// RequestSiterankAnalysisJSONBody defines parameters for RequestSiterankAnalysis.
type RequestSiterankAnalysisJSONBody struct {
	OfferId string `json:"offerId"`
}

// RequestSiterankAnalysisJSONRequestBody defines body for RequestSiterankAnalysis for application/json ContentType.
type RequestSiterankAnalysisJSONRequestBody RequestSiterankAnalysisJSONBody
