// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Notification defines model for Notification.
type Notification struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	Message   string    `json:"message"`
	Title     string    `json:"title"`
	Type      string    `json:"type"`
}

// ListRecentNotificationsParams defines parameters for ListRecentNotifications.
type ListRecentNotificationsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}
