# 应用配置
app:
  name: "autoads-v3"
  debug: true
  port: 8080
  version: "3.0.0"

# 数据库配置
database:
  type: "mysql"
  host: "dbprovider.sg-members-1.clawcloudrun.com"
  port: 30354
  username: "root"
  password: "jtl85fn8"
  database: "autoads"
  charset: "utf8mb4"
  timezone: "Local"
  pool:
    max_idle: 10
    max_open: 100
    max_lifetime: 3600

  # 兼容 gofly-admin gform 的数据库配置（默认分组：default）
  default:
    type: "mysql"
    hostname: "dbprovider.sg-members-1.clawcloudrun.com"
    hostport: "30354"
    username: "root"
    password: "jtl85fn8"
    dbname: "autoads"
    charset: "utf8mb4"
    timezone: "Local"

# Redis配置
redis:
  enable: true
  host: "dbprovider.sg-members-1.clawcloudrun.com"
  port: 32284
  password: "9xdjb8nf"
  db: 1
  pool_size: 100
  prefix: "autoads:"

# JWT配置
jwt:
  secret: "your-jwt-secret-key-xxx-here"
  expires_in: 7200  # 2小时
  refresh_expires_in: 604800  # 7天

# 日志配置
log:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, file
  file:
    filename: "logs/autoads.log"
    max_size: 100  # MB
    max_backups: 10
    max_age: 30  # days
    compress: true

# 缓存配置
cache:
  default_expire: 3600  # 默认过期时间（秒）
  memory_size: 1000    # 内存缓存大小
  redis_prefix: "autoads:cache:"
  
# HTTP客户端配置
http:
  timeout: 30  # 默认超时时间（秒）
  max_idle_conns: 100
  max_idle_conns_per_host: 10
  idle_conn_timeout: 90
  
# API限流配置
rate_limit:
  enabled: true
  requests_per_minute: 60
  burst: 10
  
# 代理配置
proxy:
  enabled: true
  pool_size: 50
  timeout: 30
  validate_interval: 300  # 代理验证间隔（秒）
  
# 第三方API配置
apis:
  google_ads:
    developer_token: "your-google-ads-developer-token"
    client_id: "your-google-ads-client-id"
    client_secret: "your-google-ads-client-secret"
    redirect_uri: "http://localhost:8080/oauth/callback"
    
# 文件上传配置
upload:
  max_size: 10485760  # 10MB
  allowed_types: [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".csv", ".xlsx"]
  path: "uploads"
  
# 任务队列配置
task_queue:
  worker_count: 10
  queue_size: 1000
  retry_times: 3
  retry_interval: 60  # 秒

# SimilarWeb API配置
similarweb:
  api_url: "https://data.similarweb.com/api/v1/data"
  rate_limit:
    # 全局速率限制
    global_per_minute: 20
    global_per_hour: 1000
    # 单用户速率限制
    user_per_minute: 5
    user_per_hour: 50
  retry:
    max_attempts: 5
    initial_delay: 1
    max_delay: 30
    backoff_factor: 2.0
