#应用信息
app:
     #版本号
     version: 1.0.0
     #名称
     title: ip地址解析属地区
     #描述
     des: 是一个离线识别ip属地，用于显示用户ip属地，不依赖第三方的api接口，本地数据包解析，解析速度快10微秒级别的查询效率。返回数据固定格式：国家|区域|省份|城市|ISP，例如：中国|0|云南省|昆明市|移动
     #标识包目录名
     name: ipregion
     #安装状态
     isinstall: true
     #安装是否为覆盖原来代码
     installcover: false
#安装前端代码
installvue:
     #安装views文件B端
     viewsfilesbusiness: 
     #安装views文件夹B端
     viewsfoldersbusiness: 
     #安装组件文件B端
     componentfilesbusiness: 
     #安装组件文件B端
     componentfoldersbusiness: 
     #安装views文件A端
     viewsfilesadmin: 
     #安装views文件夹A端
     viewsfoldersadmin: 
     #安装组件文件A端
     componentfilesadmin: 
     #安装组件文件A端
     componentfoldersadmin: 
#后端代码
installgo:
     #安装app下代码文件夹（多个,分开）
     appfolders: 
     #安装utils工具类代码文件
     utilsfiles: ipregion.go
     #合法性验证-目录取消验证
     noVerifyAPIRoot: 
sqldb:
     #数据库表名称（多个,分开）
     packtables: 
     #b端菜单ID
     businessmenuids: 
     #a端菜单ID
     adminmenuids: 
