name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches: [ main ]
    paths:
      - 'firebase.json'
      - '.firebaserc'
      - 'apps/frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Hosting (rewrite to Cloud Run frontend)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: 'gen-lang-client-0944935873'
          channelId: 'live'
