name: Deploy Frontend (Firebase Hosting)

on:
  push:
    branches: [ main, production ]
    tags: [ 'v*' ]
  workflow_dispatch:

concurrency:
  group: deploy-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/frontend/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Decide Hosting target
        id: decide
        shell: bash
        run: |
          if [[ "$GITHUB_REF" == refs/heads/main ]]; then
            TARGET="autoads-preview"
          else
            TARGET="autoads-prod"
          fi
          echo "target=${TARGET}" >> "$GITHUB_OUTPUT"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ vars.GCP_PROJECT_ID }}'
          target: '${{ steps.decide.outputs.target }}'
      - name: Cache Turbo build artifacts
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            apps/frontend/.next/cache
          key: ${{ runner.os }}-turbo-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.ref }}-
            ${{ runner.os }}-turbo-
