openapi: 3.0.0
info:
  title: Offer Service
  version: 1.0.0
  description: Manages the global offer library.
paths:
  /api/v1/offers:
    get:
      summary: List all offers for the current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of offers
    post:
      summary: Create a new offer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                originalUrl:
                  type: string
      responses:
        '201':
          description: Offer created successfully
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
